# Generated by Django 6.1 on 2026-08-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_class_conversation_conversationparticipant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group')], default='private', max_length=10),
        ),
    ]
