# Generated by Django 6.1 on 2026-08-20 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_conversation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='class_obj',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='class_obj',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='class_obj',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='uploaded_at',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='teachingassignment',
            old_name='class_obj',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='teachingassignment',
            old_name='subject',
            new_name='subject_id',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='school',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='guardian_name',
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='profile_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default='Primary', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='class_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.class'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentstudentlink',
            name='accepted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualifications',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
